Added Toad_Hollow
myelinviolin/NineSpringsBlog pull request #12
Opened 2023-09-07 08:33 UTC by Yashh56

Fixes #10

2023-09-07 14:16 UTC, myelinviolin commented on businesses/Toad_Hollow_Nursery/index.qmd
> +categories: [Nursery]
change category to "Gardening"

2023-09-07 14:17 UTC, myelinviolin commented on businesses/Toad_Hollow_Nursery/index.qmd
> +description: Local Nursery and Gardern
Change Description to "Local Native Plant Nursery"

2023-09-07 14:20 UTC, myelinviolin commented on businesses/Toad_Hollow_Nursery/leaf.webp
Please change to this [logo](https://static.wixstatic.com/media/d3de1a_72a1a50a713d43f6b35e84892909d399~mv2.png/v1/crop/x_312,y_223,w_894,h_1304/fill/w_96,h_140,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/3_18%20picture%20logo%20only%20-%20Cropped%20smaller.png)

2023-09-07 14:21 UTC, myelinviolin commented on businesses/Toad_Hollow_Nursery/index.qmd
Please add their business description from the webpage so it is not all images. People need to know what they are about just by looking at this page.

2023-09-07 14:22 UTC, myelinviolin requested changes
I think I have to leave this comment here so the review is complete so it becomes your turn to address the comments.

2023-09-07 14:27 UTC, Yashh56 commented on businesses/Toad_Hollow_Nursery/index.qmd
Only Description ?

2023-09-07 14:28 UTC, Yashh56 commented
I will make this change ASAP !!

2023-09-11 13:11 UTC, myelinviolin approved these changes
closes #10

2023-09-11 13:11 UTC, merged